// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: models/order_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // uuid
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // uuid
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // raw json as string
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`       // RFC3339
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`       // RFC3339
	Bucket        int32                  `protobuf:"varint,8,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderModel) Reset() {
	*x = OrderModel{}
	mi := &file_models_order_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderModel) ProtoMessage() {}

func (x *OrderModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_order_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderModel.ProtoReflect.Descriptor instead.
func (*OrderModel) Descriptor() ([]byte, []int) {
	return file_models_order_model_proto_rawDescGZIP(), []int{0}
}

func (x *OrderModel) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderModel) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderModel) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderModel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderModel) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *OrderModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderModel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *OrderModel) GetBucket() int32 {
	if x != nil {
		return x.Bucket
	}
	return 0
}

var File_models_order_model_proto protoreflect.FileDescriptor

const file_models_order_model_proto_rawDesc = "" +
	"\n" +
	"\x18models/order_model.proto\x12\x10orders.models.v1\"\xe9\x01\n" +
	"\n" +
	"OrderModel\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\tR\vpayloadJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x16\n" +
	"\x06bucket\x18\b \x01(\x05R\x06bucketB1Z/github.com/ivkhr/orderstream/internal/pb/modelsb\x06proto3"

var (
	file_models_order_model_proto_rawDescOnce sync.Once
	file_models_order_model_proto_rawDescData []byte
)

func file_models_order_model_proto_rawDescGZIP() []byte {
	file_models_order_model_proto_rawDescOnce.Do(func() {
		file_models_order_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_order_model_proto_rawDesc), len(file_models_order_model_proto_rawDesc)))
	})
	return file_models_order_model_proto_rawDescData
}

var file_models_order_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_order_model_proto_goTypes = []any{
	(*OrderModel)(nil), // 0: orders.models.v1.OrderModel
}
var file_models_order_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_order_model_proto_init() }
func file_models_order_model_proto_init() {
	if File_models_order_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_order_model_proto_rawDesc), len(file_models_order_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_order_model_proto_goTypes,
		DependencyIndexes: file_models_order_model_proto_depIdxs,
		MessageInfos:      file_models_order_model_proto_msgTypes,
	}.Build()
	File_models_order_model_proto = out.File
	file_models_order_model_proto_goTypes = nil
	file_models_order_model_proto_depIdxs = nil
}
