packages:
    github.com/ivkhr/orderstream/internal/services/ordersService:
        config:
            dir: "{{.InterfaceDir}}/mocks"
            filename: "{{.InterfaceName}}.go"
            outpkg: "mocks"
        interfaces:
            OrdersStorage:
            OrdersEventsPublisher:
            AckWaitRegistry:
    github.com/ivkhr/orderstream/services/worker/internal/services/worker:
        config:
            dir: "{{.InterfaceDir}}/mocks"
            filename: "{{.InterfaceName}}.go"
            outpkg: "mocks"
        interfaces:
            Storage:


