// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orders_api/orders.proto

package orders_api

import (
	models "github.com/ivkhr/orderstream/services/api_service/internal/pb/models"
	_ "github.com/ivkhr/orderstream/services/api_service/internal/pb/google/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_orders_api_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_api_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_orders_api_orders_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_orders_api_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_api_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_orders_api_orders_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpsertOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// empty or "0" => create
	OrderId       string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                              // optional; "deleted" => soft-delete
	PayloadJson   string `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertOrderRequest) Reset() {
	*x = UpsertOrderRequest{}
	mi := &file_orders_api_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertOrderRequest) ProtoMessage() {}

func (x *UpsertOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_api_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertOrderRequest.ProtoReflect.Descriptor instead.
func (*UpsertOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_api_orders_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpsertOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertOrderRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpsertOrderRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type UpsertOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // created|updated|deleted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertOrderResponse) Reset() {
	*x = UpsertOrderResponse{}
	mi := &file_orders_api_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertOrderResponse) ProtoMessage() {}

func (x *UpsertOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_api_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertOrderResponse.ProtoReflect.Descriptor instead.
func (*UpsertOrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_api_orders_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpsertOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetOrderByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDRequest) Reset() {
	*x = GetOrderByIDRequest{}
	mi := &file_orders_api_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDRequest) ProtoMessage() {}

func (x *GetOrderByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_api_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByIDRequest) Descriptor() ([]byte, []int) {
	return file_orders_api_orders_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderByIDRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *models.OrderModel     `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDResponse) Reset() {
	*x = GetOrderByIDResponse{}
	mi := &file_orders_api_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDResponse) ProtoMessage() {}

func (x *GetOrderByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_api_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrderByIDResponse) Descriptor() ([]byte, []int) {
	return file_orders_api_orders_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderByIDResponse) GetOrder() *models.OrderModel {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderByExternalIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // query param
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByExternalIDRequest) Reset() {
	*x = GetOrderByExternalIDRequest{}
	mi := &file_orders_api_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByExternalIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByExternalIDRequest) ProtoMessage() {}

func (x *GetOrderByExternalIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_api_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByExternalIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByExternalIDRequest) Descriptor() ([]byte, []int) {
	return file_orders_api_orders_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderByExternalIDRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *GetOrderByExternalIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetOrderByExternalIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *models.OrderModel     `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByExternalIDResponse) Reset() {
	*x = GetOrderByExternalIDResponse{}
	mi := &file_orders_api_orders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByExternalIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByExternalIDResponse) ProtoMessage() {}

func (x *GetOrderByExternalIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_api_orders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByExternalIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrderByExternalIDResponse) Descriptor() ([]byte, []int) {
	return file_orders_api_orders_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderByExternalIDResponse) GetOrder() *models.OrderModel {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_orders_api_orders_proto protoreflect.FileDescriptor

const file_orders_api_orders_proto_rawDesc = "" +
	"\n" +
	"\x17orders_api/orders.proto\x12\x11orders.service.v1\x1a\x18models/order_model.proto\x1a\x1cgoogle/api/annotations.proto\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x83\x01\n" +
	"\x12UpsertOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\"H\n" +
	"\x13UpsertOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"0\n" +
	"\x13GetOrderByIDRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"J\n" +
	"\x14GetOrderByIDResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orders.models.v1.OrderModelR\x05order\"W\n" +
	"\x1bGetOrderByExternalIDRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"R\n" +
	"\x1cGetOrderByExternalIDResponse\x122\n" +
	"\x05order\x18\x01 \x01(\v2\x1c.orders.models.v1.OrderModelR\x05order2\x83\x04\n" +
	"\rOrdersService\x12^\n" +
	"\x06Health\x12 .orders.service.v1.HealthRequest\x1a!.orders.service.v1.HealthResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/health\x12p\n" +
	"\vUpsertOrder\x12%.orders.service.v1.UpsertOrderRequest\x1a&.orders.service.v1.UpsertOrderResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/orders\x12{\n" +
	"\fGetOrderByID\x12&.orders.service.v1.GetOrderByIDRequest\x1a'.orders.service.v1.GetOrderByIDResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/orders/{order_id}\x12\xa2\x01\n" +
	"\x14GetOrderByExternalID\x12..orders.service.v1.GetOrderByExternalIDRequest\x1a/.orders.service.v1.GetOrderByExternalIDResponse\")\x82\xd3\xe4\x93\x02#\x12!/orders/by-external/{external_id}B5Z3github.com/ivkhr/orderstream/internal/pb/orders_apib\x06proto3"

var (
	file_orders_api_orders_proto_rawDescOnce sync.Once
	file_orders_api_orders_proto_rawDescData []byte
)

func file_orders_api_orders_proto_rawDescGZIP() []byte {
	file_orders_api_orders_proto_rawDescOnce.Do(func() {
		file_orders_api_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_api_orders_proto_rawDesc), len(file_orders_api_orders_proto_rawDesc)))
	})
	return file_orders_api_orders_proto_rawDescData
}

var file_orders_api_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_orders_api_orders_proto_goTypes = []any{
	(*HealthRequest)(nil),                // 0: orders.service.v1.HealthRequest
	(*HealthResponse)(nil),               // 1: orders.service.v1.HealthResponse
	(*UpsertOrderRequest)(nil),           // 2: orders.service.v1.UpsertOrderRequest
	(*UpsertOrderResponse)(nil),          // 3: orders.service.v1.UpsertOrderResponse
	(*GetOrderByIDRequest)(nil),          // 4: orders.service.v1.GetOrderByIDRequest
	(*GetOrderByIDResponse)(nil),         // 5: orders.service.v1.GetOrderByIDResponse
	(*GetOrderByExternalIDRequest)(nil),  // 6: orders.service.v1.GetOrderByExternalIDRequest
	(*GetOrderByExternalIDResponse)(nil), // 7: orders.service.v1.GetOrderByExternalIDResponse
	(*models.OrderModel)(nil),            // 8: orders.models.v1.OrderModel
}
var file_orders_api_orders_proto_depIdxs = []int32{
	8, // 0: orders.service.v1.GetOrderByIDResponse.order:type_name -> orders.models.v1.OrderModel
	8, // 1: orders.service.v1.GetOrderByExternalIDResponse.order:type_name -> orders.models.v1.OrderModel
	0, // 2: orders.service.v1.OrdersService.Health:input_type -> orders.service.v1.HealthRequest
	2, // 3: orders.service.v1.OrdersService.UpsertOrder:input_type -> orders.service.v1.UpsertOrderRequest
	4, // 4: orders.service.v1.OrdersService.GetOrderByID:input_type -> orders.service.v1.GetOrderByIDRequest
	6, // 5: orders.service.v1.OrdersService.GetOrderByExternalID:input_type -> orders.service.v1.GetOrderByExternalIDRequest
	1, // 6: orders.service.v1.OrdersService.Health:output_type -> orders.service.v1.HealthResponse
	3, // 7: orders.service.v1.OrdersService.UpsertOrder:output_type -> orders.service.v1.UpsertOrderResponse
	5, // 8: orders.service.v1.OrdersService.GetOrderByID:output_type -> orders.service.v1.GetOrderByIDResponse
	7, // 9: orders.service.v1.OrdersService.GetOrderByExternalID:output_type -> orders.service.v1.GetOrderByExternalIDResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_orders_api_orders_proto_init() }
func file_orders_api_orders_proto_init() {
	if File_orders_api_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_api_orders_proto_rawDesc), len(file_orders_api_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_api_orders_proto_goTypes,
		DependencyIndexes: file_orders_api_orders_proto_depIdxs,
		MessageInfos:      file_orders_api_orders_proto_msgTypes,
	}.Build()
	File_orders_api_orders_proto = out.File
	file_orders_api_orders_proto_goTypes = nil
	file_orders_api_orders_proto_depIdxs = nil
}
