// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/ivkhr/orderstream/services/worker/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, o
func (_m *MockStorage) Create(ctx context.Context, o *models.Order) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Order) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type MockStorage_Create_Call struct {
	*mock.Call
}

func (_e *MockStorage_Expecter) Create(ctx interface{}, o interface{}) *MockStorage_Create_Call {
	return &MockStorage_Create_Call{Call: _e.mock.On("Create", ctx, o)}
}

func (_c *MockStorage_Create_Call) Run(run func(ctx context.Context, o *models.Order)) *MockStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Order))
	})
	return _c
}

func (_c *MockStorage_Create_Call) Return(_a0 error) *MockStorage_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Create_Call) RunAndReturn(run func(context.Context, *models.Order) error) *MockStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrder provides a mock function with given fields: ctx, id
func (_m *MockStorage) DeleteOrder(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type MockStorage_DeleteOrder_Call struct {
	*mock.Call
}

func (_e *MockStorage_Expecter) DeleteOrder(ctx interface{}, id interface{}) *MockStorage_DeleteOrder_Call {
	return &MockStorage_DeleteOrder_Call{Call: _e.mock.On("DeleteOrder", ctx, id)}
}

func (_c *MockStorage_DeleteOrder_Call) Run(run func(ctx context.Context, id string)) *MockStorage_DeleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteOrder_Call) Return(_a0 error) *MockStorage_DeleteOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteOrder_Call) RunAndReturn(run func(context.Context, string) error) *MockStorage_DeleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetByExternalID provides a mock function with given fields: ctx, externalID, userID
func (_m *MockStorage) GetByExternalID(ctx context.Context, externalID string, userID uuid.UUID) (*models.Order, error) {
	ret := _m.Called(ctx, externalID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByExternalID")
	}

	var r0 *models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (*models.Order, error)); ok {
		return rf(ctx, externalID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *models.Order); ok {
		r0 = rf(ctx, externalID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, externalID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockStorage_GetByExternalID_Call struct {
	*mock.Call
}

func (_e *MockStorage_Expecter) GetByExternalID(ctx interface{}, externalID interface{}, userID interface{}) *MockStorage_GetByExternalID_Call {
	return &MockStorage_GetByExternalID_Call{Call: _e.mock.On("GetByExternalID", ctx, externalID, userID)}
}

func (_c *MockStorage_GetByExternalID_Call) Run(run func(ctx context.Context, externalID string, userID uuid.UUID)) *MockStorage_GetByExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorage_GetByExternalID_Call) Return(_a0 *models.Order, _a1 error) *MockStorage_GetByExternalID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetByExternalID_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) (*models.Order, error)) *MockStorage_GetByExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockStorage) GetByID(ctx context.Context, id uuid.UUID) (*models.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockStorage_GetByID_Call struct {
	*mock.Call
}

func (_e *MockStorage_Expecter) GetByID(ctx interface{}, id interface{}) *MockStorage_GetByID_Call {
	return &MockStorage_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockStorage_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStorage_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorage_GetByID_Call) Return(_a0 *models.Order, _a1 error) *MockStorage_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Order, error)) *MockStorage_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, o
func (_m *MockStorage) Update(ctx context.Context, o *models.Order) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Order) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type MockStorage_Update_Call struct {
	*mock.Call
}

func (_e *MockStorage_Expecter) Update(ctx interface{}, o interface{}) *MockStorage_Update_Call {
	return &MockStorage_Update_Call{Call: _e.mock.On("Update", ctx, o)}
}

func (_c *MockStorage_Update_Call) Run(run func(ctx context.Context, o *models.Order)) *MockStorage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Order))
	})
	return _c
}

func (_c *MockStorage_Update_Call) Return(_a0 error) *MockStorage_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Update_Call) RunAndReturn(run func(context.Context, *models.Order) error) *MockStorage_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockStorage) UpdateStatus(ctx context.Context, id string, status string) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type MockStorage_UpdateStatus_Call struct {
	*mock.Call
}

func (_e *MockStorage_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockStorage_UpdateStatus_Call {
	return &MockStorage_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockStorage_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status string)) *MockStorage_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_UpdateStatus_Call) Return(_a0 error) *MockStorage_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateStatus_Call) RunAndReturn(run func(context.Context, string, string) error) *MockStorage_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, o
func (_m *MockStorage) Upsert(ctx context.Context, o *models.Order) (bool, error) {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Order) (bool, error)); ok {
		return rf(ctx, o)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Order) bool); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Order) error); ok {
		r1 = rf(ctx, o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockStorage_Upsert_Call struct {
	*mock.Call
}

func (_e *MockStorage_Expecter) Upsert(ctx interface{}, o interface{}) *MockStorage_Upsert_Call {
	return &MockStorage_Upsert_Call{Call: _e.mock.On("Upsert", ctx, o)}
}

func (_c *MockStorage_Upsert_Call) Run(run func(ctx context.Context, o *models.Order)) *MockStorage_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Order))
	})
	return _c
}

func (_c *MockStorage_Upsert_Call) Return(_a0 bool, _a1 error) *MockStorage_Upsert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Upsert_Call) RunAndReturn(run func(context.Context, *models.Order) (bool, error)) *MockStorage_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}


