// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockAckWaitRegistry is an autogenerated mock type for the AckWaitRegistry type
type MockAckWaitRegistry struct {
	mock.Mock
}

type MockAckWaitRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAckWaitRegistry) EXPECT() *MockAckWaitRegistry_Expecter {
	return &MockAckWaitRegistry_Expecter{mock: &_m.Mock}
}

// Register provides a mock function with given fields: orderID
func (_m *MockAckWaitRegistry) Register(orderID string) (<-chan struct{}, func()) {
	ret := _m.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 <-chan struct{}
	var r1 func()
	if rf, ok := ret.Get(0).(func(string) (<-chan struct{}, func())); ok {
		return rf(orderID)
	}
	if rf, ok := ret.Get(0).(func(string) <-chan struct{}); ok {
		r0 = rf(orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) func()); ok {
		r1 = rf(orderID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}

	return r0, r1
}

// MockAckWaitRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAckWaitRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - orderID string
func (_e *MockAckWaitRegistry_Expecter) Register(orderID interface{}) *MockAckWaitRegistry_Register_Call {
	return &MockAckWaitRegistry_Register_Call{Call: _e.mock.On("Register", orderID)}
}

func (_c *MockAckWaitRegistry_Register_Call) Run(run func(orderID string)) *MockAckWaitRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAckWaitRegistry_Register_Call) Return(ch <-chan struct{}, cleanup func()) *MockAckWaitRegistry_Register_Call {
	_c.Call.Return(ch, cleanup)
	return _c
}

func (_c *MockAckWaitRegistry_Register_Call) RunAndReturn(run func(string) (<-chan struct{}, func())) *MockAckWaitRegistry_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAckWaitRegistry creates a new instance of MockAckWaitRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAckWaitRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAckWaitRegistry {
	mock := &MockAckWaitRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
