// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/ivkhr/orderstream/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockOrdersEventsPublisher is an autogenerated mock type for the OrdersEventsPublisher type
type MockOrdersEventsPublisher struct {
	mock.Mock
}

type MockOrdersEventsPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrdersEventsPublisher) EXPECT() *MockOrdersEventsPublisher_Expecter {
	return &MockOrdersEventsPublisher_Expecter{mock: &_m.Mock}
}

// PublishOrderEvent provides a mock function with given fields: ctx, event
func (_m *MockOrdersEventsPublisher) PublishOrderEvent(ctx context.Context, event *models.OrderEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishOrderEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.OrderEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrdersEventsPublisher_PublishOrderEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishOrderEvent'
type MockOrdersEventsPublisher_PublishOrderEvent_Call struct {
	*mock.Call
}

// PublishOrderEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event *models.OrderEvent
func (_e *MockOrdersEventsPublisher_Expecter) PublishOrderEvent(ctx interface{}, event interface{}) *MockOrdersEventsPublisher_PublishOrderEvent_Call {
	return &MockOrdersEventsPublisher_PublishOrderEvent_Call{Call: _e.mock.On("PublishOrderEvent", ctx, event)}
}

func (_c *MockOrdersEventsPublisher_PublishOrderEvent_Call) Run(run func(ctx context.Context, event *models.OrderEvent)) *MockOrdersEventsPublisher_PublishOrderEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.OrderEvent))
	})
	return _c
}

func (_c *MockOrdersEventsPublisher_PublishOrderEvent_Call) Return(_a0 error) *MockOrdersEventsPublisher_PublishOrderEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrdersEventsPublisher_PublishOrderEvent_Call) RunAndReturn(run func(context.Context, *models.OrderEvent) error) *MockOrdersEventsPublisher_PublishOrderEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrdersEventsPublisher creates a new instance of MockOrdersEventsPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrdersEventsPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrdersEventsPublisher {
	mock := &MockOrdersEventsPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
