// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockOrdersEventsPublisher is an autogenerated mock type for the OrdersEventsPublisher type
type MockOrdersEventsPublisher struct {
	mock.Mock
}

type MockOrdersEventsPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrdersEventsPublisher) EXPECT() *MockOrdersEventsPublisher_Expecter {
	return &MockOrdersEventsPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, value
func (_m *MockOrdersEventsPublisher) Publish(ctx context.Context, value []byte) error {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrdersEventsPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockOrdersEventsPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - value []byte
func (_e *MockOrdersEventsPublisher_Expecter) Publish(ctx interface{}, value interface{}) *MockOrdersEventsPublisher_Publish_Call {
	return &MockOrdersEventsPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, value)}
}

func (_c *MockOrdersEventsPublisher_Publish_Call) Run(run func(ctx context.Context, value []byte)) *MockOrdersEventsPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockOrdersEventsPublisher_Publish_Call) Return(_a0 error) *MockOrdersEventsPublisher_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrdersEventsPublisher_Publish_Call) RunAndReturn(run func(context.Context, []byte) error) *MockOrdersEventsPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrdersEventsPublisher creates a new instance of MockOrdersEventsPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrdersEventsPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrdersEventsPublisher {
	mock := &MockOrdersEventsPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
