// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/ivkhr/orderstream/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockOrdersStorage is an autogenerated mock type for the OrdersStorage type
type MockOrdersStorage struct {
	mock.Mock
}

type MockOrdersStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrdersStorage) EXPECT() *MockOrdersStorage_Expecter {
	return &MockOrdersStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, o
func (_m *MockOrdersStorage) Create(ctx context.Context, o *models.Order) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Order) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrdersStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrdersStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - o *models.Order
func (_e *MockOrdersStorage_Expecter) Create(ctx interface{}, o interface{}) *MockOrdersStorage_Create_Call {
	return &MockOrdersStorage_Create_Call{Call: _e.mock.On("Create", ctx, o)}
}

func (_c *MockOrdersStorage_Create_Call) Run(run func(ctx context.Context, o *models.Order)) *MockOrdersStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Order))
	})
	return _c
}

func (_c *MockOrdersStorage_Create_Call) Return(_a0 error) *MockOrdersStorage_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrdersStorage_Create_Call) RunAndReturn(run func(context.Context, *models.Order) error) *MockOrdersStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrder provides a mock function with given fields: ctx, id
func (_m *MockOrdersStorage) DeleteOrder(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrdersStorage_DeleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrder'
type MockOrdersStorage_DeleteOrder_Call struct {
	*mock.Call
}

// DeleteOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrdersStorage_Expecter) DeleteOrder(ctx interface{}, id interface{}) *MockOrdersStorage_DeleteOrder_Call {
	return &MockOrdersStorage_DeleteOrder_Call{Call: _e.mock.On("DeleteOrder", ctx, id)}
}

func (_c *MockOrdersStorage_DeleteOrder_Call) Run(run func(ctx context.Context, id string)) *MockOrdersStorage_DeleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrdersStorage_DeleteOrder_Call) Return(_a0 error) *MockOrdersStorage_DeleteOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrdersStorage_DeleteOrder_Call) RunAndReturn(run func(context.Context, string) error) *MockOrdersStorage_DeleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetByExternalID provides a mock function with given fields: ctx, externalID, userID
func (_m *MockOrdersStorage) GetByExternalID(ctx context.Context, externalID string, userID uuid.UUID) (*models.Order, error) {
	ret := _m.Called(ctx, externalID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByExternalID")
	}

	var r0 *models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (*models.Order, error)); ok {
		return rf(ctx, externalID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *models.Order); ok {
		r0 = rf(ctx, externalID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, externalID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrdersStorage_GetByExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByExternalID'
type MockOrdersStorage_GetByExternalID_Call struct {
	*mock.Call
}

// GetByExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
//   - userID uuid.UUID
func (_e *MockOrdersStorage_Expecter) GetByExternalID(ctx interface{}, externalID interface{}, userID interface{}) *MockOrdersStorage_GetByExternalID_Call {
	return &MockOrdersStorage_GetByExternalID_Call{Call: _e.mock.On("GetByExternalID", ctx, externalID, userID)}
}

func (_c *MockOrdersStorage_GetByExternalID_Call) Run(run func(ctx context.Context, externalID string, userID uuid.UUID)) *MockOrdersStorage_GetByExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrdersStorage_GetByExternalID_Call) Return(_a0 *models.Order, _a1 error) *MockOrdersStorage_GetByExternalID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrdersStorage_GetByExternalID_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) (*models.Order, error)) *MockOrdersStorage_GetByExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockOrdersStorage) GetByID(ctx context.Context, id uuid.UUID) (*models.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrdersStorage_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockOrdersStorage_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOrdersStorage_Expecter) GetByID(ctx interface{}, id interface{}) *MockOrdersStorage_GetByID_Call {
	return &MockOrdersStorage_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockOrdersStorage_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOrdersStorage_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrdersStorage_GetByID_Call) Return(_a0 *models.Order, _a1 error) *MockOrdersStorage_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrdersStorage_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Order, error)) *MockOrdersStorage_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, o
func (_m *MockOrdersStorage) Update(ctx context.Context, o *models.Order) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Order) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrdersStorage_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOrdersStorage_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - o *models.Order
func (_e *MockOrdersStorage_Expecter) Update(ctx interface{}, o interface{}) *MockOrdersStorage_Update_Call {
	return &MockOrdersStorage_Update_Call{Call: _e.mock.On("Update", ctx, o)}
}

func (_c *MockOrdersStorage_Update_Call) Run(run func(ctx context.Context, o *models.Order)) *MockOrdersStorage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Order))
	})
	return _c
}

func (_c *MockOrdersStorage_Update_Call) Return(_a0 error) *MockOrdersStorage_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrdersStorage_Update_Call) RunAndReturn(run func(context.Context, *models.Order) error) *MockOrdersStorage_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockOrdersStorage) UpdateStatus(ctx context.Context, id string, status string) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrdersStorage_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockOrdersStorage_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status string
func (_e *MockOrdersStorage_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockOrdersStorage_UpdateStatus_Call {
	return &MockOrdersStorage_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockOrdersStorage_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status string)) *MockOrdersStorage_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOrdersStorage_UpdateStatus_Call) Return(_a0 error) *MockOrdersStorage_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrdersStorage_UpdateStatus_Call) RunAndReturn(run func(context.Context, string, string) error) *MockOrdersStorage_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrdersStorage creates a new instance of MockOrdersStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrdersStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrdersStorage {
	mock := &MockOrdersStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
